site_name: Edmunds

pages:

  - Introduction: index.md

  - Core Concepts:
    - Application Middleware: coreconcepts/applicationmiddleware.md
    - Service Providers: coreconcepts/serviceproviders.md

  - Getting Started:
    - Installation: gettingstarted/installation.md
    - Configuration: gettingstarted/configuration.md
    - Debugging and Profiling: gettingstarted/debuggingandprofiling.md
    - Errors and Logging: gettingstarted/errorsandlogging.md
    - Console: gettingstarted/console.md

  - Http:
    - Request Middleware: http/requestmiddleware.md
    - Routing: http/routing.md
    - Request: http/request.md
    - Input and Validation: http/inputandvalidation.md
    - Session: http/session.md
    - Response: http/response.md
    - Visitor: http/visitor.md

  - Data:
    - Storage: data/storage.md
    - Database: data/database.md
    - ORM: data/orm.md
    - Migrations: data/migrations.md
    - Caching: data/caching.md

  - Localization:
    - Localization: localization/localization.md
    - Location: localization/location.md
    - Formatting: localization/formatting.md
    - Translations: localization/translations.md

  - Authentication:
    - Introduction: auth/introduction.md
    - Token Authentication: auth/token.md
    - Session Authentication: auth/session.md
    - Basic HTTP Authentication: auth/basic.md
    - Roles: auth/roles.md

  - Testing:
    - Getting Started: testing/gettingstarted.md

theme:
  name: 'material'
